# Generated by Django 5.0.6 on 2024-05-12 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_materia', models.CharField(max_length=100)),
                ('clave_mat', models.CharField(max_length=20)),
                ('creditos', models.CharField(max_length=10)),
                ('grupo', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
