# Generated by Django 5.0.6 on 2024-05-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_alumno', models.CharField(max_length=100)),
                ('num_control', models.CharField(max_length=10, null=True)),
                ('semestre', models.CharField(max_length=10)),
            ],
        ),
    ]
